CREATE TABLE IF NOT EXISTS produto (
    id BIGSERIAL PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL,
    nome VARCHAR(160) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'EM_DIGITACAO',
    preco NUMERIC(14, 2),
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_produto_codigo ON produto (codigo);
CREATE INDEX IF NOT EXISTS idx_produto_status ON produto (status);
