<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260508005000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Assinantes no login e recuperacao de senha.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE auth_subscriber (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) NOT NULL, name VARCHAR(160) NOT NULL, document VARCHAR(40) DEFAULT NULL, principal BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_auth_subscriber_code ON auth_subscriber (code)');
        $this->addSql('CREATE INDEX idx_auth_subscriber_enabled ON auth_subscriber (enabled, principal)');

        $this->addSql('CREATE TABLE auth_user_subscriber (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_tenant_id VARCHAR(80) NOT NULL, username VARCHAR(160) NOT NULL, subscriber_code VARCHAR(80) NOT NULL, default_subscriber BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, permission_overrides JSON NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_auth_user_subscriber ON auth_user_subscriber (user_tenant_id, username, subscriber_code)');
        $this->addSql('CREATE INDEX idx_auth_user_subscriber_user ON auth_user_subscriber (user_tenant_id, username, enabled)');
        $this->addSql('CREATE INDEX idx_auth_user_subscriber_subscriber ON auth_user_subscriber (subscriber_code, enabled)');

        $this->addSql('CREATE TABLE auth_login_challenge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(120) NOT NULL, status VARCHAR(30) NOT NULL, user_payload JSON NOT NULL, provider_code VARCHAR(80) NOT NULL, provider_type VARCHAR(40) NOT NULL, remember BOOLEAN NOT NULL, default_subscriber_code VARCHAR(80) DEFAULT NULL, available_subscribers JSON NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_auth_login_challenge_hash ON auth_login_challenge (token_hash)');
        $this->addSql('CREATE INDEX idx_auth_login_challenge_status ON auth_login_challenge (status, expires_at)');

        $this->addSql('CREATE TABLE auth_password_reset_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_tenant_id VARCHAR(80) NOT NULL, username VARCHAR(160) NOT NULL, token_hash VARCHAR(120) NOT NULL, status VARCHAR(30) NOT NULL, metadata JSON NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_auth_password_reset_token_hash ON auth_password_reset_token (token_hash)');
        $this->addSql('CREATE INDEX idx_auth_password_reset_user ON auth_password_reset_token (user_tenant_id, username, status)');
        $this->addSql('CREATE INDEX idx_auth_password_reset_expiration ON auth_password_reset_token (status, expires_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE auth_password_reset_token');
        $this->addSql('DROP TABLE auth_login_challenge');
        $this->addSql('DROP TABLE auth_user_subscriber');
        $this->addSql('DROP TABLE auth_subscriber');
    }
}
