<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260506120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Estrutura inicial do backend runtime, construtor e clientes.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE builder_program (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, title VARCHAR(160) NOT NULL, module VARCHAR(120) DEFAULT NULL, program_type VARCHAR(40) NOT NULL, screen_id VARCHAR(160) DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_builder_program_code ON builder_program (code)');

        $this->addSql('CREATE TABLE builder_entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, name VARCHAR(160) NOT NULL, entity_type VARCHAR(30) NOT NULL, table_name VARCHAR(160) DEFAULT NULL, source_name VARCHAR(160) DEFAULT NULL, status VARCHAR(20) NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_builder_entity_code ON builder_entity (code)');

        $this->addSql('CREATE TABLE builder_field (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, builder_entity_id INT NOT NULL, code VARCHAR(120) NOT NULL, label VARCHAR(160) NOT NULL, data_type VARCHAR(40) NOT NULL, database_type VARCHAR(80) DEFAULT NULL, length INT DEFAULT NULL, precision_value INT DEFAULT NULL, scale_value INT DEFAULT NULL, required BOOLEAN NOT NULL, primary_key BOOLEAN NOT NULL, position INT NOT NULL, options JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BUILDER_FIELD_ENTITY ON builder_field (builder_entity_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_builder_field_entity_code ON builder_field (builder_entity_id, code)');
        $this->addSql('ALTER TABLE builder_field ADD CONSTRAINT FK_BUILDER_FIELD_ENTITY FOREIGN KEY (builder_entity_id) REFERENCES builder_entity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE screen_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, screen_id VARCHAR(160) NOT NULL, page_type VARCHAR(30) NOT NULL, schema_version VARCHAR(20) NOT NULL, definition JSON NOT NULL, status VARCHAR(20) NOT NULL, version VARCHAR(40) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_screen_definition_screen_id ON screen_definition (screen_id)');

        $this->addSql('CREATE TABLE runtime_endpoint (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, screen_id VARCHAR(160) NOT NULL, endpoint_id VARCHAR(160) NOT NULL, handler VARCHAR(160) NOT NULL, permission VARCHAR(160) DEFAULT NULL, enabled BOOLEAN NOT NULL, config JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_runtime_endpoint_screen_endpoint ON runtime_endpoint (screen_id, endpoint_id)');

        $this->addSql('CREATE TABLE user_layout_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, screen_id VARCHAR(160) NOT NULL, preference_type VARCHAR(30) NOT NULL, preference_id VARCHAR(80) NOT NULL, name VARCHAR(160) NOT NULL, default_preference BOOLEAN NOT NULL, payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_user_layout_lookup ON user_layout_preference (tenant_id, user_id, screen_id, preference_type)');

        $this->addSql('CREATE TABLE import_export_mapping (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, name VARCHAR(160) NOT NULL, direction VARCHAR(20) NOT NULL, target_type VARCHAR(40) NOT NULL, target_code VARCHAR(160) NOT NULL, format VARCHAR(40) NOT NULL, mapping JSON NOT NULL, status VARCHAR(20) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_import_export_mapping_code ON import_export_mapping (code)');

        $this->addSql('CREATE TABLE cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(120) NOT NULL, email VARCHAR(150) DEFAULT NULL, status VARCHAR(20) NOT NULL, tipo_pessoa VARCHAR(2) NOT NULL, uf VARCHAR(2) DEFAULT NULL, cidade VARCHAR(120) DEFAULT NULL, razao_social VARCHAR(150) DEFAULT NULL, cnpj VARCHAR(18) DEFAULT NULL, data_cadastro DATE DEFAULT NULL, valor_total NUMERIC(14, 2) DEFAULT NULL, qtde_pedidos INT DEFAULT NULL, observacao TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cliente');
        $this->addSql('DROP TABLE import_export_mapping');
        $this->addSql('DROP TABLE user_layout_preference');
        $this->addSql('DROP TABLE runtime_endpoint');
        $this->addSql('DROP TABLE screen_definition');
        $this->addSql('DROP TABLE builder_field');
        $this->addSql('DROP TABLE builder_entity');
        $this->addSql('DROP TABLE builder_program');
    }
}
