<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260528160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria cache materializado para consultas analytics e BI.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE runtime_analytics_cache (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, screen_id VARCHAR(160) NOT NULL, dataset_id VARCHAR(120) NOT NULL, view_id VARCHAR(120) NOT NULL DEFAULT '', filter_fingerprint VARCHAR(64) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'ready', row_count INT NOT NULL DEFAULT 0, payload JSON NOT NULL, metadata JSON NOT NULL, last_error TEXT DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, refreshed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_runtime_analytics_cache_key ON runtime_analytics_cache (tenant_id, screen_id, dataset_id, view_id, filter_fingerprint)');
        $this->addSql('CREATE INDEX idx_runtime_analytics_cache_status ON runtime_analytics_cache (tenant_id, status, expires_at)');
        $this->addSql('CREATE INDEX idx_runtime_analytics_cache_screen ON runtime_analytics_cache (screen_id, dataset_id, refreshed_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE runtime_analytics_cache');
    }
}
