<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260508002000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria tokens persistentes para manter login.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE auth_remember_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, username VARCHAR(160) NOT NULL, token_hash VARCHAR(120) NOT NULL, status VARCHAR(30) NOT NULL, device_name VARCHAR(160) DEFAULT NULL, user_agent TEXT DEFAULT NULL, metadata JSON NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoke_reason VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_auth_remember_token_hash ON auth_remember_token (token_hash)');
        $this->addSql('CREATE INDEX idx_auth_remember_token_user ON auth_remember_token (tenant_id, user_id, status)');
        $this->addSql('CREATE INDEX idx_auth_remember_token_expiration ON auth_remember_token (expires_at, status)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS auth_remember_token');
    }
}
