<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260508004000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adiciona preferencias estruturadas de grid, filtros, ordenacoes, agrupamentos e template mobile.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_grid_layout_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, screen_id VARCHAR(160) NOT NULL, layout_id VARCHAR(80) NOT NULL, name VARCHAR(160) NOT NULL, default_preference BOOLEAN NOT NULL, definition_hash VARCHAR(120) DEFAULT NULL, columns_order JSON NOT NULL, hidden_columns JSON NOT NULL, column_widths JSON NOT NULL, frozen_columns JSON NOT NULL, added_columns JSON NOT NULL, sort_config JSON NOT NULL, filter_config JSON DEFAULT NULL, group_config JSON NOT NULL, group_aggregates JSON NOT NULL, mobile_template JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_user_grid_layout_lookup ON user_grid_layout_preference (tenant_id, user_id, screen_id, default_preference)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_grid_layout_preference ON user_grid_layout_preference (tenant_id, user_id, screen_id, layout_id)');

        $this->addSql('CREATE TABLE user_sort_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, screen_id VARCHAR(160) NOT NULL, sort_id VARCHAR(80) NOT NULL, name VARCHAR(160) NOT NULL, default_preference BOOLEAN NOT NULL, sort_config JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_user_sort_lookup ON user_sort_preference (tenant_id, user_id, screen_id, default_preference)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_sort_preference ON user_sort_preference (tenant_id, user_id, screen_id, sort_id)');

        $this->addSql('CREATE TABLE user_filter_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, screen_id VARCHAR(160) NOT NULL, filter_id VARCHAR(80) NOT NULL, name VARCHAR(160) NOT NULL, default_preference BOOLEAN NOT NULL, filters JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_user_filter_lookup ON user_filter_preference (tenant_id, user_id, screen_id, default_preference)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_filter_preference ON user_filter_preference (tenant_id, user_id, screen_id, filter_id)');

        $this->addSql('CREATE TABLE user_group_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, screen_id VARCHAR(160) NOT NULL, group_id VARCHAR(80) NOT NULL, name VARCHAR(160) NOT NULL, default_preference BOOLEAN NOT NULL, group_config JSON NOT NULL, aggregates JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_user_group_lookup ON user_group_preference (tenant_id, user_id, screen_id, default_preference)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_group_preference ON user_group_preference (tenant_id, user_id, screen_id, group_id)');

        $this->addSql('CREATE TABLE user_mobile_grid_template_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, screen_id VARCHAR(160) NOT NULL, template_id VARCHAR(80) NOT NULL, name VARCHAR(160) NOT NULL, default_preference BOOLEAN NOT NULL, title_field VARCHAR(120) DEFAULT NULL, subtitle_field VARCHAR(120) DEFAULT NULL, badge_fields JSON NOT NULL, field_positions JSON NOT NULL, tabs JSON NOT NULL, payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_user_mobile_grid_template_lookup ON user_mobile_grid_template_preference (tenant_id, user_id, screen_id, default_preference)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_mobile_grid_template_preference ON user_mobile_grid_template_preference (tenant_id, user_id, screen_id, template_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_mobile_grid_template_preference');
        $this->addSql('DROP TABLE user_group_preference');
        $this->addSql('DROP TABLE user_filter_preference');
        $this->addSql('DROP TABLE user_sort_preference');
        $this->addSql('DROP TABLE user_grid_layout_preference');
    }
}
