<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260510113000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Historico e rollback de modelagem para builder_entity.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE builder_entity_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, builder_entity_code VARCHAR(120) NOT NULL, entity_name VARCHAR(160) NOT NULL, entity_type VARCHAR(30) NOT NULL, table_name VARCHAR(160) DEFAULT NULL, revision INT NOT NULL, status VARCHAR(20) NOT NULL, action VARCHAR(20) NOT NULL, source_version_id INT DEFAULT NULL, snapshot JSON NOT NULL, change_summary TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_builder_entity_version_entity ON builder_entity_version (builder_entity_code, status, updated_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_builder_entity_version_revision ON builder_entity_version (builder_entity_code, revision)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE builder_entity_version');
    }
}
