<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260507143000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Fila async com Messenger Doctrine e rastreamento runtime_async_job.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE runtime_async_job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, transaction_id INT DEFAULT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, user_name VARCHAR(160) DEFAULT NULL, session_id VARCHAR(160) NOT NULL, screen_id VARCHAR(160) NOT NULL, program_id VARCHAR(160) DEFAULT NULL, entity_code VARCHAR(120) DEFAULT NULL, record_id VARCHAR(120) DEFAULT NULL, action_id VARCHAR(160) DEFAULT NULL, job_type VARCHAR(120) NOT NULL, status VARCHAR(30) NOT NULL, attempts INT NOT NULL, last_error TEXT DEFAULT NULL, payload JSON NOT NULL, result JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_RUNTIME_ASYNC_JOB_TRANSACTION ON runtime_async_job (transaction_id)');
        $this->addSql('CREATE INDEX idx_runtime_async_job_status ON runtime_async_job (tenant_id, status, created_at)');
        $this->addSql('CREATE INDEX idx_runtime_async_job_record ON runtime_async_job (entity_code, record_id)');
        $this->addSql('CREATE INDEX idx_runtime_async_job_type ON runtime_async_job (job_type, status)');
        $this->addSql('ALTER TABLE runtime_async_job ADD CONSTRAINT FK_RUNTIME_ASYNC_JOB_TRANSACTION FOREIGN KEY (transaction_id) REFERENCES runtime_transaction (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE runtime_async_job');
    }
}
