<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260507100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Auditoria runtime, politicas de semaforo, locks, sessoes e mensagens.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE runtime_transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, user_name VARCHAR(160) DEFAULT NULL, session_id VARCHAR(160) NOT NULL, screen_id VARCHAR(160) NOT NULL, program_id VARCHAR(160) DEFAULT NULL, entity_code VARCHAR(120) DEFAULT NULL, record_id VARCHAR(120) DEFAULT NULL, endpoint_id VARCHAR(160) NOT NULL, action_id VARCHAR(160) DEFAULT NULL, operation VARCHAR(80) NOT NULL, status VARCHAR(30) NOT NULL, lock_token VARCHAR(120) DEFAULT NULL, request_context JSON NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_runtime_transaction_user ON runtime_transaction (tenant_id, user_id, started_at)');
        $this->addSql('CREATE INDEX idx_runtime_transaction_record ON runtime_transaction (entity_code, record_id)');

        $this->addSql('CREATE TABLE runtime_transaction_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, transaction_id INT NOT NULL, user_id VARCHAR(120) NOT NULL, event_type VARCHAR(80) NOT NULL, message TEXT DEFAULT NULL, before_data JSON NOT NULL, after_data JSON NOT NULL, diff_data JSON NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_RUNTIME_TRANSACTION_LOG_TRANSACTION ON runtime_transaction_log (transaction_id)');
        $this->addSql('CREATE INDEX idx_runtime_transaction_log_event ON runtime_transaction_log (event_type, created_at)');
        $this->addSql('ALTER TABLE runtime_transaction_log ADD CONSTRAINT FK_RUNTIME_TRANSACTION_LOG_TRANSACTION FOREIGN KEY (transaction_id) REFERENCES runtime_transaction (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE runtime_lock_policy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) DEFAULT NULL, program_id VARCHAR(160) DEFAULT NULL, entity_code VARCHAR(120) DEFAULT NULL, action_id VARCHAR(160) DEFAULT NULL, mode VARCHAR(20) NOT NULL, stale_policy VARCHAR(20) NOT NULL, lock_ttl_seconds INT NOT NULL, heartbeat_interval_seconds INT NOT NULL, enabled BOOLEAN NOT NULL, handler_id VARCHAR(160) DEFAULT NULL, condition_config JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_runtime_lock_policy_scope ON runtime_lock_policy (tenant_id, program_id, entity_code, action_id)');

        $this->addSql('CREATE TABLE runtime_record_lock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, transaction_id INT DEFAULT NULL, tenant_id VARCHAR(80) NOT NULL, program_id VARCHAR(160) DEFAULT NULL, entity_code VARCHAR(120) NOT NULL, record_id VARCHAR(120) NOT NULL, action_id VARCHAR(160) DEFAULT NULL, lock_token VARCHAR(120) NOT NULL, locked_by_user_id VARCHAR(120) NOT NULL, locked_by_user_name VARCHAR(160) DEFAULT NULL, session_id VARCHAR(160) NOT NULL, mode VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL, acquired_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, released_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, metadata JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_RUNTIME_RECORD_LOCK_TOKEN ON runtime_record_lock (lock_token)');
        $this->addSql('CREATE INDEX IDX_RUNTIME_RECORD_LOCK_TRANSACTION ON runtime_record_lock (transaction_id)');
        $this->addSql('CREATE INDEX idx_runtime_record_lock_lookup ON runtime_record_lock (tenant_id, entity_code, record_id, status)');
        $this->addSql('ALTER TABLE runtime_record_lock ADD CONSTRAINT FK_RUNTIME_RECORD_LOCK_TRANSACTION FOREIGN KEY (transaction_id) REFERENCES runtime_transaction (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE runtime_user_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, user_name VARCHAR(160) DEFAULT NULL, session_id VARCHAR(160) NOT NULL, status VARCHAR(30) NOT NULL, revoked_by VARCHAR(120) DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoke_reason VARCHAR(255) DEFAULT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_runtime_user_session_tenant_session ON runtime_user_session (tenant_id, session_id)');
        $this->addSql('CREATE INDEX idx_runtime_user_session_user ON runtime_user_session (tenant_id, user_id, status)');

        $this->addSql('CREATE TABLE runtime_user_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, sender_user_id VARCHAR(120) NOT NULL, sender_user_name VARCHAR(160) DEFAULT NULL, target_user_id VARCHAR(120) NOT NULL, target_session_id VARCHAR(160) DEFAULT NULL, type VARCHAR(40) NOT NULL, severity VARCHAR(30) NOT NULL, title VARCHAR(160) NOT NULL, message TEXT NOT NULL, status VARCHAR(30) NOT NULL, action_required BOOLEAN NOT NULL, metadata JSON NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, acknowledged_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_runtime_user_message_user ON runtime_user_message (tenant_id, target_user_id, status)');
        $this->addSql('CREATE INDEX idx_runtime_user_message_session ON runtime_user_message (tenant_id, target_session_id, status)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE runtime_user_message');
        $this->addSql('DROP TABLE runtime_user_session');
        $this->addSql('DROP TABLE runtime_record_lock');
        $this->addSql('DROP TABLE runtime_lock_policy');
        $this->addSql('DROP TABLE runtime_transaction_log');
        $this->addSql('DROP TABLE runtime_transaction');
    }
}
