<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260529130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria storage versionado para pipelines semanticos de analytics.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE runtime_analytics_pipeline_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, screen_id VARCHAR(160) NOT NULL, pipeline_id VARCHAR(120) NOT NULL, version_no INT NOT NULL, definition_hash VARCHAR(64) NOT NULL, definition_json JSON NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'draft', created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_runtime_analytics_pipeline_version_hash ON runtime_analytics_pipeline_version (tenant_id, screen_id, pipeline_id, definition_hash)');
        $this->addSql('CREATE INDEX idx_runtime_analytics_pipeline_version_key ON runtime_analytics_pipeline_version (tenant_id, screen_id, pipeline_id, version_no)');

        $this->addSql("CREATE TABLE runtime_analytics_pipeline_execution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, screen_id VARCHAR(160) NOT NULL, pipeline_id VARCHAR(120) NOT NULL, pipeline_version_id INT NOT NULL, execution_code VARCHAR(120) NOT NULL, mode VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL, working_dataset_json JSON DEFAULT NULL, metadata_json JSON DEFAULT NULL, row_count INT NOT NULL DEFAULT 0, error_message TEXT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_runtime_analytics_pipeline_execution_code ON runtime_analytics_pipeline_execution (execution_code)');
        $this->addSql('CREATE INDEX idx_runtime_analytics_pipeline_execution_lookup ON runtime_analytics_pipeline_execution (tenant_id, screen_id, pipeline_id, created_at)');

        $this->addSql("CREATE TABLE runtime_analytics_pipeline_execution_step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, execution_code VARCHAR(120) NOT NULL, step_id VARCHAR(120) NOT NULL, step_type VARCHAR(30) NOT NULL, position INT NOT NULL, status VARCHAR(30) NOT NULL, row_count INT NOT NULL DEFAULT 0, output_columns_json JSON DEFAULT NULL, metadata_json JSON DEFAULT NULL, error_message TEXT DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX idx_runtime_analytics_pipeline_step_execution ON runtime_analytics_pipeline_execution_step (execution_code, position)');

        $this->addSql("CREATE TABLE runtime_analytics_published_dataset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, screen_id VARCHAR(160) NOT NULL, pipeline_id VARCHAR(120) NOT NULL, dataset_id VARCHAR(120) NOT NULL, active_version_no INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_runtime_analytics_published_dataset_key ON runtime_analytics_published_dataset (tenant_id, screen_id, dataset_id)');

        $this->addSql("CREATE TABLE runtime_analytics_published_dataset_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, published_dataset_id INT NOT NULL, tenant_id VARCHAR(80) NOT NULL, screen_id VARCHAR(160) NOT NULL, pipeline_id VARCHAR(120) NOT NULL, dataset_id VARCHAR(120) NOT NULL, version_no INT NOT NULL, status VARCHAR(30) NOT NULL, execution_code VARCHAR(120) NOT NULL, schema_json JSON NOT NULL, data_json JSON NOT NULL, row_count INT NOT NULL DEFAULT 0, fingerprint VARCHAR(64) NOT NULL, metadata_json JSON DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, superseded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rolled_back_from_version_no INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_runtime_analytics_published_dataset_version_key ON runtime_analytics_published_dataset_version (tenant_id, screen_id, dataset_id, version_no)');
        $this->addSql('CREATE INDEX idx_runtime_analytics_published_dataset_active ON runtime_analytics_published_dataset_version (tenant_id, screen_id, dataset_id, status)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE runtime_analytics_published_dataset_version');
        $this->addSql('DROP TABLE runtime_analytics_published_dataset');
        $this->addSql('DROP TABLE runtime_analytics_pipeline_execution_step');
        $this->addSql('DROP TABLE runtime_analytics_pipeline_execution');
        $this->addSql('DROP TABLE runtime_analytics_pipeline_version');
    }
}
