<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260508001000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria modulo simples de parametros com listas de opcoes.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE system_option_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, name VARCHAR(160) NOT NULL, description TEXT DEFAULT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_system_option_list_code ON system_option_list (code)');
        $this->addSql('CREATE INDEX idx_system_option_list_enabled ON system_option_list (enabled)');

        $this->addSql('CREATE TABLE system_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, option_list_id INT NOT NULL, code VARCHAR(120) NOT NULL, description VARCHAR(255) NOT NULL, position INT NOT NULL, enabled BOOLEAN NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_system_option_code_per_list ON system_option (option_list_id, code)');
        $this->addSql('CREATE INDEX idx_system_option_lookup ON system_option (option_list_id, enabled)');
        $this->addSql('ALTER TABLE system_option ADD CONSTRAINT FK_SYSTEM_OPTION_LIST FOREIGN KEY (option_list_id) REFERENCES system_option_list (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE system_parameter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, option_list_id INT DEFAULT NULL, code VARCHAR(120) NOT NULL, name VARCHAR(160) NOT NULL, description TEXT DEFAULT NULL, data_type VARCHAR(40) NOT NULL, required BOOLEAN NOT NULL, default_value JSON DEFAULT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_system_parameter_code ON system_parameter (code)');
        $this->addSql('CREATE INDEX idx_system_parameter_type ON system_parameter (data_type, enabled)');
        $this->addSql('CREATE INDEX idx_system_parameter_option_list ON system_parameter (option_list_id)');
        $this->addSql('ALTER TABLE system_parameter ADD CONSTRAINT FK_SYSTEM_PARAMETER_OPTION_LIST FOREIGN KEY (option_list_id) REFERENCES system_option_list (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE system_parameter_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, parameter_id INT NOT NULL, establishment_code VARCHAR(120) DEFAULT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, value JSON DEFAULT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_system_parameter_value_scope ON system_parameter_value (parameter_id, establishment_code, enabled, starts_at)');
        $this->addSql('CREATE INDEX idx_system_parameter_value_establishment ON system_parameter_value (establishment_code)');
        $this->addSql('ALTER TABLE system_parameter_value ADD CONSTRAINT FK_SYSTEM_PARAMETER_VALUE_PARAMETER FOREIGN KEY (parameter_id) REFERENCES system_parameter (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS system_parameter_value');
        $this->addSql('DROP TABLE IF EXISTS system_parameter');
        $this->addSql('DROP TABLE IF EXISTS system_option');
        $this->addSql('DROP TABLE IF EXISTS system_option_list');
    }
}
