<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260514152000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria runtime_support_request para o backend do atendimento da Home.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE runtime_support_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, protocol VARCHAR(40) NOT NULL, requester_user_id VARCHAR(120) NOT NULL, requester_user_name VARCHAR(160) DEFAULT NULL, sector_id VARCHAR(80) NOT NULL, sector_name VARCHAR(160) DEFAULT NULL, priority VARCHAR(30) NOT NULL, subject VARCHAR(200) NOT NULL, description TEXT NOT NULL, status VARCHAR(30) NOT NULL, assigned_user_id VARCHAR(120) DEFAULT NULL, assigned_user_name VARCHAR(160) DEFAULT NULL, request_context JSON NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_runtime_support_request_protocol ON runtime_support_request (tenant_id, protocol)');
        $this->addSql('CREATE INDEX idx_runtime_support_request_user ON runtime_support_request (tenant_id, requester_user_id, status)');
        $this->addSql('CREATE INDEX idx_runtime_support_request_assigned ON runtime_support_request (tenant_id, assigned_user_id, status)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE runtime_support_request');
    }
}
