<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260510143000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Snapshots versionados genericos para cadastros mestres.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE runtime_entity_record_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_code VARCHAR(120) NOT NULL, record_id VARCHAR(120) NOT NULL, revision INT NOT NULL, snapshot_hash VARCHAR(64) DEFAULT NULL, snapshot JSON NOT NULL, source_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_runtime_entity_record_version_record ON runtime_entity_record_version (entity_code, record_id, revision)');
        $this->addSql('CREATE INDEX idx_runtime_entity_record_version_lookup ON runtime_entity_record_version (entity_code, record_id, created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE runtime_entity_record_version');
    }
}
