<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260531113000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria tabela de frequencia de lookup por usuario/tela/filtro.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_lookup_usage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, screen_id VARCHAR(160) NOT NULL, filter_id VARCHAR(80) NOT NULL, field_name VARCHAR(120) DEFAULT NULL, lookup_value VARCHAR(160) NOT NULL, lookup_text VARCHAR(255) NOT NULL, hits INT NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_lookup_usage ON user_lookup_usage (tenant_id, user_id, screen_id, filter_id, lookup_value)');
        $this->addSql('CREATE INDEX idx_user_lookup_usage_lookup ON user_lookup_usage (tenant_id, user_id, screen_id, filter_id, hits, last_used_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_lookup_usage');
    }
}
