<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260508003000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adiciona situacoes e transicoes por entidade.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE builder_entity ADD situation_enabled BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE builder_entity ADD situation_field_code VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE builder_entity ALTER situation_enabled DROP DEFAULT');
        $this->addSql('CREATE TABLE builder_entity_situation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, builder_entity_id INT NOT NULL, code VARCHAR(80) NOT NULL, label VARCHAR(160) NOT NULL, description TEXT DEFAULT NULL, position INT NOT NULL, is_initial BOOLEAN NOT NULL, is_final BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_builder_entity_situation_entity ON builder_entity_situation (builder_entity_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_builder_entity_situation_code ON builder_entity_situation (builder_entity_id, code)');
        $this->addSql('CREATE TABLE builder_entity_situation_transition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, builder_entity_id INT NOT NULL, from_code VARCHAR(80) DEFAULT NULL, to_code VARCHAR(80) NOT NULL, action_id VARCHAR(120) NOT NULL, label VARCHAR(160) DEFAULT NULL, permission VARCHAR(160) DEFAULT NULL, position INT NOT NULL, enabled BOOLEAN NOT NULL, guard_config JSON NOT NULL, effects JSON NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_builder_entity_situation_transition_entity ON builder_entity_situation_transition (builder_entity_id)');
        $this->addSql('CREATE INDEX idx_builder_entity_situation_transition_lookup ON builder_entity_situation_transition (builder_entity_id, from_code, action_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_builder_entity_situation_transition ON builder_entity_situation_transition (builder_entity_id, from_code, to_code, action_id)');
        $this->addSql('ALTER TABLE builder_entity_situation ADD CONSTRAINT fk_builder_entity_situation_entity FOREIGN KEY (builder_entity_id) REFERENCES builder_entity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE builder_entity_situation_transition ADD CONSTRAINT fk_builder_entity_situation_transition_entity FOREIGN KEY (builder_entity_id) REFERENCES builder_entity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE builder_entity_situation_transition DROP CONSTRAINT fk_builder_entity_situation_transition_entity');
        $this->addSql('ALTER TABLE builder_entity_situation DROP CONSTRAINT fk_builder_entity_situation_entity');
        $this->addSql('DROP TABLE builder_entity_situation_transition');
        $this->addSql('DROP TABLE builder_entity_situation');
        $this->addSql('ALTER TABLE builder_entity DROP situation_field_code');
        $this->addSql('ALTER TABLE builder_entity DROP situation_enabled');
    }
}
