<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260511103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adiciona lock de edicao para o construtor visual.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE builder_editor_lock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scope_type VARCHAR(30) NOT NULL, scope_code VARCHAR(160) NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, user_name VARCHAR(160) DEFAULT NULL, session_id VARCHAR(160) NOT NULL, lock_token VARCHAR(120) NOT NULL, status VARCHAR(20) NOT NULL, display_name VARCHAR(255) DEFAULT NULL, acquired_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, released_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_builder_editor_lock_token ON builder_editor_lock (lock_token)');
        $this->addSql('CREATE INDEX idx_builder_editor_lock_scope ON builder_editor_lock (scope_type, scope_code, status, expires_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE builder_editor_lock');
    }
}
