<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260604103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria tabelas de pedido de venda para master-detail.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE pedido_venda (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(30) NOT NULL, cliente VARCHAR(160) NOT NULL, data_emissao DATE NOT NULL, status VARCHAR(30) NOT NULL, valor_total NUMERIC(14, 2) NOT NULL DEFAULT 0, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_pedido_venda_numero ON pedido_venda (numero)');

        $this->addSql("CREATE TABLE pedido_venda_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pedido_id INT NOT NULL, produto VARCHAR(180) NOT NULL, quantidade NUMERIC(14, 3) NOT NULL, valor_unitario NUMERIC(14, 2) NOT NULL, valor_total NUMERIC(14, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX idx_pedido_venda_item_pedido ON pedido_venda_item (pedido_id)');
        $this->addSql('ALTER TABLE pedido_venda_item ADD CONSTRAINT fk_pedido_venda_item_pedido FOREIGN KEY (pedido_id) REFERENCES pedido_venda (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("CREATE TABLE pedido_venda_parcela (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pedido_id INT NOT NULL, numero INT NOT NULL, vencimento DATE NOT NULL, valor NUMERIC(14, 2) NOT NULL, situacao VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX idx_pedido_venda_parcela_pedido ON pedido_venda_parcela (pedido_id)');
        $this->addSql('ALTER TABLE pedido_venda_parcela ADD CONSTRAINT fk_pedido_venda_parcela_pedido FOREIGN KEY (pedido_id) REFERENCES pedido_venda (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pedido_venda_parcela DROP CONSTRAINT fk_pedido_venda_parcela_pedido');
        $this->addSql('ALTER TABLE pedido_venda_item DROP CONSTRAINT fk_pedido_venda_item_pedido');
        $this->addSql('DROP TABLE pedido_venda_parcela');
        $this->addSql('DROP TABLE pedido_venda_item');
        $this->addSql('DROP TABLE pedido_venda');
    }
}
