<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260509093000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Historico de versoes para construtor visual de programas.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE builder_program_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, program_code VARCHAR(120) NOT NULL, program_title VARCHAR(160) NOT NULL, module VARCHAR(120) DEFAULT NULL, page_type VARCHAR(30) NOT NULL, builder_entity_code VARCHAR(120) NOT NULL, screen_id VARCHAR(160) NOT NULL, version VARCHAR(40) NOT NULL, status VARCHAR(20) NOT NULL, subtitle VARCHAR(160) DEFAULT NULL, icon VARCHAR(80) DEFAULT NULL, permission_prefix VARCHAR(160) DEFAULT NULL, allow_create BOOLEAN NOT NULL, allow_update BOOLEAN NOT NULL, allow_delete BOOLEAN NOT NULL, change_summary TEXT DEFAULT NULL, builder_config JSON NOT NULL, generated_definition JSON NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_builder_program_version_program ON builder_program_version (program_code, status, updated_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_builder_program_version_code_version ON builder_program_version (program_code, version)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE builder_program_version');
    }
}
