<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260507200000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria tabelas de autenticacao local e configuracao de provedores.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE IF NOT EXISTS auth_provider_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) NOT NULL, type VARCHAR(40) NOT NULL, name VARCHAR(160) NOT NULL, enabled BOOLEAN NOT NULL, priority INT NOT NULL, config JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_auth_provider_code ON auth_provider_config (code)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_auth_provider_type ON auth_provider_config (type, enabled)');

        $this->addSql("CREATE TABLE IF NOT EXISTS auth_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, username VARCHAR(160) NOT NULL, normalized_username VARCHAR(160) NOT NULL, display_name VARCHAR(160) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, password_hash VARCHAR(255) DEFAULT NULL, status VARCHAR(30) NOT NULL, groups JSON NOT NULL, permissions JSON NOT NULL, auth_source VARCHAR(40) NOT NULL, force_password_change BOOLEAN NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX IF NOT EXISTS uniq_auth_user_tenant_username ON auth_user (tenant_id, normalized_username)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_auth_user_status ON auth_user (tenant_id, status)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS auth_user');
        $this->addSql('DROP TABLE IF EXISTS auth_provider_config');
    }
}
