<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260514130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria catalogo runtime de notificacoes e destinatarios por usuario.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE runtime_notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) NOT NULL, code VARCHAR(120) NOT NULL, title VARCHAR(160) NOT NULL, message TEXT NOT NULL, category VARCHAR(80) NOT NULL, severity VARCHAR(30) NOT NULL, status VARCHAR(30) NOT NULL, action_required BOOLEAN NOT NULL, target_user_ids JSON NOT NULL, target_groups JSON NOT NULL, link_program_id VARCHAR(160) DEFAULT NULL, link_screen_id VARCHAR(160) DEFAULT NULL, metadata JSON NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_runtime_notification_tenant_code ON runtime_notification (tenant_id, code)');
        $this->addSql('CREATE INDEX idx_runtime_notification_status ON runtime_notification (tenant_id, status, published_at)');
        $this->addSql("CREATE TABLE runtime_notification_recipient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notification_id INT NOT NULL, tenant_id VARCHAR(80) NOT NULL, user_id VARCHAR(120) NOT NULL, user_name VARCHAR(160) NOT NULL, source_type VARCHAR(30) NOT NULL, source_key VARCHAR(160) NOT NULL, status VARCHAR(30) NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_runtime_notification_recipient_user ON runtime_notification_recipient (notification_id, user_id)');
        $this->addSql('CREATE INDEX idx_runtime_notification_recipient_status ON runtime_notification_recipient (tenant_id, user_id, status)');
        $this->addSql('CREATE INDEX idx_runtime_notification_recipient_notification ON runtime_notification_recipient (notification_id)');
        $this->addSql('ALTER TABLE runtime_notification_recipient ADD CONSTRAINT FK_RUNTIME_NOTIFICATION_RECIPIENT_NOTIFICATION FOREIGN KEY (notification_id) REFERENCES runtime_notification (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE runtime_notification_recipient DROP CONSTRAINT FK_RUNTIME_NOTIFICATION_RECIPIENT_NOTIFICATION');
        $this->addSql('DROP TABLE runtime_notification_recipient');
        $this->addSql('DROP TABLE runtime_notification');
    }
}
