<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260528123000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria tabelas de solicitacoes LGPD, validacao publica, evidencias e politicas de retencao.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE privacy_subject_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, protocol VARCHAR(40) NOT NULL, tenant_id VARCHAR(80) NOT NULL, source_channel VARCHAR(40) NOT NULL, requester_name VARCHAR(160) DEFAULT NULL, requester_email VARCHAR(180) NOT NULL, requester_document VARCHAR(40) DEFAULT NULL, subject_identifier VARCHAR(160) DEFAULT NULL, request_type VARCHAR(40) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(40) NOT NULL, priority VARCHAR(30) NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, assigned_to VARCHAR(120) DEFAULT NULL, decision VARCHAR(40) DEFAULT NULL, decision_reason TEXT DEFAULT NULL, response_message TEXT DEFAULT NULL, retention_blocked BOOLEAN NOT NULL DEFAULT FALSE, analysis_result JSON NOT NULL, evidence JSON NOT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_privacy_subject_request_protocol ON privacy_subject_request (protocol)');
        $this->addSql('CREATE INDEX idx_privacy_subject_request_tenant_status ON privacy_subject_request (tenant_id, status, priority, created_at)');
        $this->addSql('CREATE INDEX idx_privacy_subject_request_subject ON privacy_subject_request (tenant_id, requester_email, requester_document, subject_identifier)');

        $this->addSql("CREATE TABLE privacy_subject_request_verification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, request_id INT NOT NULL, code_hash VARCHAR(255) NOT NULL, attempts INT NOT NULL DEFAULT 0, max_attempts INT NOT NULL DEFAULT 5, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX idx_privacy_verification_request ON privacy_subject_request_verification (request_id, expires_at)');
        $this->addSql('ALTER TABLE privacy_subject_request_verification ADD CONSTRAINT FK_PRIVACY_VERIFICATION_REQUEST FOREIGN KEY (request_id) REFERENCES privacy_subject_request (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("CREATE TABLE privacy_subject_request_evidence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, request_id INT NOT NULL, tenant_id VARCHAR(80) NOT NULL, evidence_type VARCHAR(40) NOT NULL, title VARCHAR(160) NOT NULL, description TEXT DEFAULT NULL, source_channel VARCHAR(40) DEFAULT NULL, external_reference VARCHAR(160) DEFAULT NULL, content TEXT DEFAULT NULL, metadata JSON NOT NULL, created_by VARCHAR(120) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX idx_privacy_evidence_request ON privacy_subject_request_evidence (request_id, created_at)');
        $this->addSql('ALTER TABLE privacy_subject_request_evidence ADD CONSTRAINT FK_PRIVACY_EVIDENCE_REQUEST FOREIGN KEY (request_id) REFERENCES privacy_subject_request (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("CREATE TABLE privacy_retention_policy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tenant_id VARCHAR(80) DEFAULT NULL, policy_code VARCHAR(120) NOT NULL, title VARCHAR(160) NOT NULL, target_type VARCHAR(40) NOT NULL, target_code VARCHAR(160) NOT NULL, retention_basis VARCHAR(80) NOT NULL, retention_days INT DEFAULT NULL, action_after_retention VARCHAR(40) NOT NULL, blocks_anonymization BOOLEAN NOT NULL DEFAULT FALSE, fiscal_required BOOLEAN NOT NULL DEFAULT FALSE, enabled BOOLEAN NOT NULL DEFAULT TRUE, notes TEXT DEFAULT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX uniq_privacy_retention_policy_code ON privacy_retention_policy (policy_code)');
        $this->addSql('CREATE INDEX idx_privacy_retention_policy_target ON privacy_retention_policy (tenant_id, target_type, target_code, enabled)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE privacy_subject_request_evidence DROP CONSTRAINT FK_PRIVACY_EVIDENCE_REQUEST');
        $this->addSql('ALTER TABLE privacy_subject_request_verification DROP CONSTRAINT FK_PRIVACY_VERIFICATION_REQUEST');
        $this->addSql('DROP TABLE privacy_retention_policy');
        $this->addSql('DROP TABLE privacy_subject_request_evidence');
        $this->addSql('DROP TABLE privacy_subject_request_verification');
        $this->addSql('DROP TABLE privacy_subject_request');
    }
}
